# Generated by Django 5.2.5 on 2025-08-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Створено'), ('COLLECTED', 'Зібрано'), ('SHIPPED', 'Відправлено'), ('ARRIVED_OFFICE', 'Прибули у відділення'), ('RECEIVED_BY_USER', 'Отримано користувачем'), ('SENT_BACK', 'Відправлено назад'), ('RECEIVED_BY_LIBRARY', 'Отримано бібліотекою'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Скасовано')], default='CREATED', max_length=32)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_until', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Створено'), ('COLLECTED', 'Зібрано'), ('SHIPPED', 'Відправлено'), ('ARRIVED_OFFICE', 'Прибули у відділення'), ('RECEIVED_BY_USER', 'Отримано користувачем'), ('SENT_BACK', 'Відправлено назад'), ('RECEIVED_BY_LIBRARY', 'Отримано бібліотекою'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Скасовано')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('NEW', 'Нова'), ('USED', 'Використовувалась'), ('FRAGILE', 'Хрупка')], max_length=16)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('NEW', 'Нова'), ('USED', 'Використовувалась'), ('FRAGILE', 'Хрупка')], max_length=16)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book', 'condition')},
            },
        ),
    ]
